{
 "title": "Redis HA Testing",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job Name",
    "query": "label_values(redis_operation_success_total, exported_job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Availability",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 1, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(redis_operation_success_total{exported_job=~\"[[job]]\"}) / max(redis_operation_total{exported_job=~\"[[job]]\"}) "
    }
   ]
  },
  {
   "title": "Total Commands",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(redis_operation_total{exported_job=~\"[[job]]\"})"
    }
   ]
  },
  {
   "title": "Failed Commands",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(redis_operation_failed_total{exported_job=~\"[[job]]\"})"
    }
   ]
  },
  {
   "title": "Successful Commands",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(redis_operation_success_total{exported_job=~\"[[job]]\"})"
    }
   ]
  },
  {
   "title": "MTTR (Seconds)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(redis_operation_mttr_histogram_seconds_sum{exported_job=~\"[[job]]\"})"
    }
   ]
  },
  {
   "title": "Average Command Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(redis_operation_durations_histogram_seconds_bucket{exported_job=~\"[[job]]\"}[2m])) by (le, operation))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Commands Per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_operation_total{exported_job=~\"[[job]]\"}[2m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(redis_operation_failed_total{exported_job=~\"[[job]]\"}[2m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(redis_operation_success_total{exported_job=~\"[[job]]\"}[2m]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Command Duration Percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(redis_operation_durations_histogram_seconds_bucket{exported_job=~\"[[job]]\"}[2m])) by (le))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(redis_operation_durations_histogram_seconds_bucket{exported_job=~\"[[job]]\"}[2m])) by (le))",
     "legendFormat": "75th Percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(redis_operation_durations_histogram_seconds_bucket{exported_job=~\"[[job]]\"}[2m])) by (le))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(redis_operation_durations_histogram_seconds_bucket{exported_job=~\"[[job]]\"}[2m])) by (le))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "Commands Per Second By Type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_operation_total{exported_job=~\"[[job]]\"}[2m])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Average MTTR Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(redis_operation_mttr_histogram_seconds_bucket{exported_job=~\"[[job]]\"}[2m])) by (le, operation))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "MTTR Duration Percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(redis_operation_mttr_histogram_seconds_bucket{exported_job=~\"[[job]]\"}[2m])) by (le))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(redis_operation_mttr_histogram_seconds_bucket{exported_job=~\"[[job]]\"}[2m])) by (le))",
     "legendFormat": "75th Percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(redis_operation_mttr_histogram_seconds_bucket{exported_job=~\"[[job]]\"}[2m])) by (le))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(redis_operation_mttr_histogram_seconds_bucket{exported_job=~\"[[job]]\"}[2m])) by (le))",
     "legendFormat": "95th Percentile"
    }
   ]
  }
 ]
}